### ISSUE TITLE
使用“mbox feature start xxx”时，分支名能考虑支持自定义吗？

### ISSUE THREAD

**Issue by smithereensarr** [MBoxPlus/mbox#10]
使用“mbox feature start xxx”时，分支名能考虑支持自定义吗？
有的时候不希望创建的feature，分支名被自动增加“feature/”前缀，哪里可以修改这个配置呢？

**Comment by Whirlwind** [comment]
有一个前缀 --prefix 参数可以改前缀。另外，你这个需求有点没看懂

**Comment by smithereensarr** [comment]
感谢，需要的就是这个--prefix参数，可以使用--prefix ''来避免自带的“feature/”前缀。
