### ISSUE TITLE
mbox pod install失败

### ISSUE THREAD

**Issue by q876911695** [MBoxPlus/mbox#12]
Bundler could not find compatible versions for gem "cocoapods":
      In Gemfile:
        mbox-cocoapods was resolved to 1.2.5, which depends on
          cocoapods (>= 1.7.0, < 1.11.0)

    Could not find gem 'cocoapods (>= 1.7.0, < 1.11.0)', which is required by gem
    'mbox-cocoapods', in locally installed gems.

以前cocoapods的版本为1.11.2，现在已经降级为1.10.1还是不行

**Comment by Whirlwind** [comment]
我们发现，使用 Bundler 2.3.x 可以正常了。可以试试

**Comment by q876911695** [comment]
使用bundler 2.3.5还是报错
<img width="1263" alt="iShot2022-01-24 09 56 28" src="https://user-images.githubusercontent.com/12725552/150710516-b4c9c696-fc8b-4d2f-8ddf-93df5739e4b4.png">
<img width="1260" alt="iShot2022-01-24 09 57 19" src="https://user-images.githubusercontent.com/12725552/150710542-75d32319-3a1a-4dbd-8e99-af550b844f06.png">

**Comment by q876911695** [comment]
已解决，在项目根目录加上Gemfile.custom文件即可
