### ISSUE TITLE
开源出来的命令行工具上可以用的吗?

### ISSUE THREAD

**Issue by BestiOSDev** [MBoxPlus/mbox#16]
MBox虽然开源了 但是没有人提 issues, 就能看出来没多人用这个. 执行脚本很多插件报错. 大厂开源工具 小白只能看的份
![image](https://user-images.githubusercontent.com/15530810/183007388-d888fbcd-e027-4fdd-a491-646c486fd87d.png)

**Comment by Whirlwind** [comment]
通过这个日志，首先有一个环境错误，可以加一个 --verbose 参数看看具体内容。
另外，Container 似乎没正确接入，需要看下 iOS 项目接入，需要指明 Podfile 路径（如果你的Podfile不在项目根目录下）

**Comment by BestiOSDev** [comment]
在看了很多文档后, 最近学会了如何使用 mbox 来管理代码仓库. 虽然没有 GUI 工具, 提供的命令行也可以完成很多工作, 给字节工作人员点赞.

**Comment by BestiOSDev** [comment]
我很早就关注了这个项目, 以前是不会用 mbox, 报错后就不用了, 在看了很多文档后, 学会了如何使用 mbox 来管理代码仓库. 虽然没有 GUI 工具, 提供的命令行也可以完成很多工作, 给字节工作人员点赞.

**Comment by BestiOSDev** [comment]
我很早就关注了这个项目, 以前是不会用 mbox, 报错后就不用了, 在看了很多文档后, 学会了如何使用 mbox 来管理代码仓库. 虽然没有 GUI 工具, 提供的命令行也可以完成很多工作, 给字节工作人员点赞. 希望字节大佬们能够维护好 mbox 这个工具

**Comment by haibarahu** [comment]
> 我很早就关注了这个项目, 以前是不会用 mbox, 报错后就不用了, 在看了很多文档后, 学会了如何使用 mbox 来管理代码仓库. 虽然没有 GUI 工具, 提供的命令行也可以完成很多工作, 给字节工作人员点赞. 希望字节大佬们能够维护好 mbox 这个工具

欢迎多给我们提意见。

**Comment by BestiOSDev** [comment]
功能挺好用的, 不太方便的地方是 mbox feature start xxx 会给所有container 创建一个 branch, 有时候 只是使用 gitlab 上别人创建过的 branch, 并不需要创建一个新的 feat 分支, 当 mbox feature remove xxx 后 在 gitlab 创建的这些feature分支并没有被删除, 如果每个人都使用不同的配置生成feature mode, 就会在 gitlab 上创建很多 feature 分支, 不利用管理.

**Comment by Whirlwind** [comment]
如果你只是一两个仓库不希望同步分支策略，你可以使用常规的Git操作的。至于未删除 feature 分支，主要是出于安全考虑，mbox 是本地工具，不会删除远端的东西，而且删除远端的分支也可能存在权限问题。一般我们采用 Feature 分支的 MR 合并到主干后，勾选 Gitlab 的 remove source branch 那个选项来实现自动删除。

**Comment by BestiOSDev** [comment]
关闭了这个 issue
