### ISSUE TITLE
brew install 失败，macOS版本问题

### ISSUE THREAD

**Issue by TyhGB** [MBoxPlus/mbox#5]
brew install mbox
Warning: You are using macOS 11.5.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

Error: Your Xcode does not support macOS 11.5.
It is either outdated or was modified.
Please update your Xcode or delete it if no updates are available.

其他信息：
macOS version：11.5.1
Xcode version：12.5.1

备注：
macOS 11.5 应该不是预发布版本吧。 现在可以更新到11.5.2了

**Comment by RyanLeeLY** [comment]
尝试下升级 homebrew。brew update

**Comment by TyhGB** [comment]
谢谢。有用，已安装

> 尝试下升级 homebrew。brew update
