### ISSUE TITLE
bundle install error 因为 gemfile 不存在 source

### ISSUE THREAD

**Issue by chrayon** [MBoxPlus/mbox#6]
bundle install
Resolving dependencies...
Your Gemfile has no gem server sources. If you need gems that are not already on your machine,
add a line like this to your Gemfile:
source 'https://rubygems.org'
Bundler could not find compatible versions for gem "cocoapods":
  In Gemfile:
    mbox-cocoapods was resolved to 1.2.5, which depends on
      cocoapods (< 1.11.0, >= 1.7.0)

Could not find gem 'cocoapods (< 1.11.0, >= 1.7.0)', which is required by gem
'mbox-cocoapods', in any of the sources.

**Comment by Whirlwind** [comment]
尝试卸载 bundler 最新版本，使用 bundler 2.2.8 试试。我得看下新版本的 Bundler 要求

**Comment by sunshinfight** [comment]
‘Your Gemfile has no gem server sources.’ 需要添加 gem 源，在 mbox 目录下添加 'Gemfile.custom'，然后编辑文本，添加`source 'https://rubygems.org'`。重新运行 `bundle install`。
或者直接使用 `mbox bundle install`
